Repository notary-now/backend_notary_now, pull requests merged in 2020-02, with the labels that each got.

#13 Heroku deployment with travis ci and add pr template
  .github/pull_request_template.md
  .gitignore
  .travis.yml
  backend_notary_now/settings.py
  notary_now_api/tests/test_sample.py
  notary_now_api/urls.py
  requirements.txt
Labels: BE, Phase 1

#21 20 Add basic readme
  README.md
Labels: BE, Phase 1, documentation

#25 23 Update Migrations with New User Model
  account/__init__.py
  account/admin.py
  account/apps.py
  account/migrations/0001_changed_user_model.py
  account/migrations/__init__.py
  account/models.py
  account/tests.py
  account/views.py
  backend_notary_now/settings.py
  notary_now_api/migrations/0001_changed_user_model.py
  notary_now_api/migrations/0001_initial.py
  notary_now_api/migrations/0003_auto_20200215_2109.py
  notary_now_api/models.py
Labels: BE, Phase 1, database migrations

#66 Update apointee to appointee wherever it was used. Add migration.
  notary_now_api/migrations/0010_auto_20200220_2257.py
  notary_now_api/models.py
  notary_now_api/views.py
Labels: BE, Phase 2, bug, database migrations, good first issue

#82 34 Get Appointment by Appointment ID
  README.md
  notary_now_api/tests.py
  notary_now_api/urls.py
  notary_now_api/views.py
Labels: BE, GET, Phase 2, documentation, endpoint, enhancement
